const state={transactions:[],assets:[],loadedFiles:new Set(),importMessages:[],transactionPage:1,demo:false};
const demoFiles=[
  new File(['日付,内容,大項目,金額,計算対象\n2026-01-05,給与,収入,280000,1\n2026-01-10,家賃,住宅,-82000,1\n2026-01-15,食料品,食費,-24000,1\n2026-01-22,電気料金,水道・光熱費,-9000,1\n2026-02-05,給与,収入,280000,1\n2026-02-12,食料品,食費,-21000,1\n2026-02-20,書籍,教養・教育,-6000,1'], 'デモ明細.csv', {type:'text/csv'}),
  new File(['日付,普通預金,投資信託,合計\n2026-01-31,420000,1300000,1720000\n2026-02-28,585000,1340000,1925000'], 'デモ資産.csv', {type:'text/csv'})
];
const yenFormatter=new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0});
const yen=n=>yenFormatter.format(n);
const text=s=>String(s??'').trim();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function parseCSV(s){const rows=[];let row=[],cell='',quote=false;for(let i=0;i<s.length;i++){const c=s[i],n=s[i+1];if(c==='"'){if(quote&&n==='"'){cell+='"';i++}else quote=!quote}else if(c===','&&!quote){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!quote){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(x=>text(x))){rows.push(row)}row=[];cell=''}else cell+=c}if(cell||row.length){row.push(cell);rows.push(row)}return rows}
function decode(file){return file.arrayBuffer().then(b=>{const bytes=new Uint8Array(b);try{return new TextDecoder('utf-8',{fatal:true}).decode(bytes)}catch{return new TextDecoder('shift-jis').decode(bytes)}})}
function classify(headers,filename=''){const h=headers.join('');if(filename.includes('資産')||filename.includes('残高')||h.includes('資産')||h.includes('純資産'))return'assets';return'transactions'}
  function parseFile(file){return decode(file).then(raw=>{const key=`${file.name}\0${raw}`;if(state.loadedFiles.has(key))return;state.loadedFiles.add(key);const rows=parseCSV(raw);if(!rows.length){state.importMessages.push(`${file.name}: ヘッダー行がありません`);return}const headers=rows[0].map(text);const type=classify(headers,file.name);if(type==='assets'){const date=headers.findIndex(x=>x.includes('日付'));const total=headers.findIndex(x=>x.includes('合計')||x.includes('総額')||x.includes('資産'));if(date<0||total<0){state.importMessages.push(`${file.name}: 資産CSVに必要な「日付」「合計・総額・資産」列がありません`);return}const breakdown=headers.map((label,index)=>({label,index})).filter(x=>x.index!==date&&x.index!==total);const incoming=rows.slice(1).map(r=>({date:text(r[date]),total:Number(text(r[total]).replace(/,/g,'')),breakdown:breakdown.map(({label,index})=>({label,value:Number(text(r[index]).replace(/,/g,''))||0}))})).filter(x=>x.date&&Number.isFinite(x.total));if(incoming.length<rows.length-1)state.importMessages.push(`${file.name}: 不正な日付または合計値の${rows.length-1-incoming.length}行を除外しました`);state.assets.push(...incoming);}else{const target=headers.findIndex(x=>x.includes('計算対象'));const date=headers.findIndex(x=>x.includes('日付'));const content=headers.findIndex(x=>x.includes('内容')||x.includes('摘要'));const amount=headers.findIndex(x=>x.includes('金額'));const category=headers.findIndex(x=>x.includes('大項目')||x.includes('カテゴリ'));if(date<0||amount<0){state.importMessages.push(`${file.name}: 明細CSVに必要な「日付」「金額」列がありません`);return}const candidates=rows.slice(1).filter(r=>target<0||text(r[target])==='1');const incoming=candidates.map(r=>({date:text(r[date]),content:text(r[content]),category:text(r[category])||'未分類',amount:Number(text(r[amount]).replace(/,/g,''))})).filter(x=>x.date&&Number.isFinite(x.amount));if(incoming.length<candidates.length)state.importMessages.push(`${file.name}: 不正な日付または金額の${candidates.length-incoming.length}行を除外しました`);state.transactions.push(...incoming);}})}
function render(){document.querySelector('#emptyState').hidden=true;document.querySelector('#dashboard').hidden=false;document.querySelector('#demoBadge').hidden=!state.demo;document.querySelector('#demoNotice').hidden=!state.demo;document.querySelector('#clearData').disabled=state.transactions.length===0&&state.assets.length===0;const ts=state.transactions;let income=0,expense=0,firstDate='',lastDate='';for(const transaction of ts){if(transaction.amount>0)income+=transaction.amount;else if(transaction.amount<0)expense-=transaction.amount;if(!firstDate||transaction.date<firstDate)firstDate=transaction.date;if(!lastDate||transaction.date>lastDate)lastDate=transaction.date}document.querySelector('#income').textContent=yen(income);document.querySelector('#expense').textContent=yen(expense);document.querySelector('#balance').textContent=yen(income-expense);document.querySelector('#period').textContent=ts.length?`${firstDate} 〜 ${lastDate}`:'—';
   document.querySelector('#loadSummary').textContent=`読み込み ${state.loadedFiles.size.toLocaleString()}ファイル・明細 ${ts.length.toLocaleString()}件`;const status=document.querySelector('#importStatus');status.hidden=!state.importMessages.length;status.innerHTML=state.importMessages.map(message=>`<div>${esc(message)}</div>`).join('');const months=[...new Set(ts.map(x=>x.date.slice(0,7)))].sort().reverse();const select=document.querySelector('#monthSelect');select.innerHTML='<option value="all">全期間</option>'+months.map(m=>`<option>${m}</option>`).join('');renderCategories();renderMonthlyTrend();renderTransactions();renderAssets()}
function filtered(){const m=document.querySelector('#monthSelect').value;return state.transactions.filter(x=>m==='all'||x.date.startsWith(m))}
function renderCategories(){const sums={};filtered().filter(x=>x.amount<0).forEach(x=>sums[x.category]=(sums[x.category]||0)+Math.abs(x.amount));const data=Object.entries(sums).sort((a,b)=>b[1]-a[1]).slice(0,8),max=data[0]?.[1]||1;document.querySelector('#categoryChart').innerHTML=data.length?data.map(([k,v])=>`<div class="bar-row"><span class="bar-label" title="${esc(k)}">${esc(k)}</span><div class="bar-track"><div class="bar-fill" style="width:${v/max*100}%"></div></div><span class="bar-value">${yen(v)}</span></div>`).join(''):'<p class="muted">支出データがありません</p>'}
function renderMonthlyTrend(){const byMonth={};for(const transaction of state.transactions){const month=transaction.date.slice(0,7);if(!/^\d{4}-\d{2}$/.test(month))continue;if(!byMonth[month])byMonth[month]={income:0,expense:0,balance:0};if(transaction.amount>=0)byMonth[month].income+=transaction.amount;else byMonth[month].expense-=transaction.amount;byMonth[month].balance+=transaction.amount}const data=Object.entries(byMonth).sort((a,b)=>a[0].localeCompare(b[0])).slice(-24),max=Math.max(1,...data.flatMap(([,values])=>[values.income,values.expense,Math.abs(values.balance)]));const chart=document.querySelector('#monthlyTrend');if(!data.length){chart.innerHTML='<p class="muted">月別に集計できる明細がありません</p>';return}chart.innerHTML=data.map(([month,values])=>{const bars=[['income','収入',values.income],['expense','支出',values.expense],['balance','収支',values.balance]];return `<div class="trend-month"><div class="trend-label">${esc(month)}</div><div class="trend-bars">${bars.map(([type,label,value])=>`<div class="trend-item"><div class="trend-track"><div class="trend-bar ${type}-bar" style="height:${Math.max(value===0?0:4,Math.abs(value)/max*100)}%" title="${esc(month)}の${label}: ${yen(value)}"></div></div><span>${yen(value)}</span></div>`).join('')}</div></div>`}).join('')}
function renderTransactions(){const q=document.querySelector('#search').value.toLowerCase();const rows=filtered().filter(x=>`${x.content} ${x.category}`.toLowerCase().includes(q)).sort((a,b)=>b.date.localeCompare(a.date));const pageSize=300;const pageCount=Math.max(1,Math.ceil(rows.length/pageSize));state.transactionPage=Math.min(state.transactionPage,pageCount);const start=(state.transactionPage-1)*pageSize;const visible=rows.slice(start,start+pageSize);document.querySelector('#transactions').innerHTML=visible.map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(x.content)||'—'}</td><td>${esc(x.category)}</td><td class="right ${x.amount>=0?'positive':'negative'}">${x.amount>=0?'+':''}${yen(x.amount)}</td></tr>`).join('')||'<tr><td colspan="4" class="muted">該当する明細がありません</td></tr>';const pagination=document.querySelector('#transactionPagination');pagination.innerHTML=rows.length>pageSize?`<span aria-live="polite">${start+1}〜${Math.min(start+pageSize,rows.length)}件 / ${rows.length}件</span><button type="button" data-page="prev" ${state.transactionPage===1?'disabled':''}>前の300件</button><span>ページ ${state.transactionPage} / ${pageCount}</span><button type="button" data-page="next" ${state.transactionPage===pageCount?'disabled':''}>次の300件</button>`:''}
  function assetDisplayData(data){if(data.length<=24)return data;const byMonth=new Map();for(const item of data){const month=item.date.slice(0,7);if(!byMonth.has(month)||byMonth.get(month).date<item.date)byMonth.set(month,item)}return [...byMonth.values()].sort((a,b)=>a.date.localeCompare(b.date)).slice(-24)}
  function renderAssets(){const chart=document.querySelector('#assetChart');const latest=document.querySelector('#assetLatest');if(!state.assets.length){latest.textContent='—';chart.innerHTML='<p class="muted">資産推移CSVを読み込むと表示されます</p>';return}const data=state.assets.slice().sort((a,b)=>a.date.localeCompare(b.date));const visible=assetDisplayData(data);const max=Math.max(...visible.map(x=>x.total)),min=Math.min(...visible.map(x=>x.total));const newest=data.at(-1);latest.textContent=`最新 ${newest.date} ${yen(newest.total)}`;chart.innerHTML=visible.map(x=>`<div class="asset-bar" data-date="${esc(x.date)}" data-value="${x.total}" title="${esc(x.date)}: ${yen(x.total)}" role="button" tabindex="0" aria-label="${esc(x.date)}の資産 ${yen(x.total)}" style="height:${Math.max(5,(x.total-min)/(max-min||1)*100)}%"></div>`).join('')+'<div id="assetTooltip" class="asset-tooltip"></div>';const tooltip=document.querySelector('#assetTooltip');document.querySelectorAll('.asset-bar').forEach((bar,index)=>{bar.addEventListener('mouseenter',()=>{const breakdown=visible[index].breakdown;tooltip.innerHTML=`<b>${esc(bar.dataset.date)}</b><br>${breakdown.map(({label,value})=>`${esc(label)}: ${yen(value)}`).join('<br>')}`;tooltip.classList.add('visible')});bar.addEventListener('mouseleave',()=>tooltip.classList.remove('visible'));const selectMonth=()=>{const month=bar.dataset.date.slice(0,7);const select=document.querySelector('#monthSelect');if([...select.options].some(option=>option.value===month)){select.value=month;renderCategories();renderTransactions();document.querySelector('#transactions').scrollIntoView({behavior:'smooth',block:'start'})}};bar.addEventListener('click',selectMonth);bar.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();selectMonth()}})})}
async function load(files){for(const f of files)await parseFile(f);render()}
async function loadDemoData(){state.demo=true;await load(demoFiles)}
async function listCsvs(path){const response=await fetch(path);if(!response.ok)throw new Error('CSV directory unavailable');const html=await response.text();const links=[...html.matchAll(/href="([^"]+)"/gi)].map(m=>decodeURIComponent(m[1]));const files=[];for(const link of links){if(link==='../'||link.startsWith('?'))continue;const url=path+link;if(link.endsWith('/'))files.push(...await listCsvs(url));else if(link.toLowerCase().endsWith('.csv'))files.push(url)}return files}
async function autoLoadCsvs(){try{const urls=await listCsvs('csvs/');if(!urls.length)return;for(const url of urls){const response=await fetch(url);const blob=await response.blob();await parseFile(new File([blob],url.split('/').at(-1),{type:'text/csv'}))}render()}catch(error){console.info('csvs auto-load skipped:',error.message)}}
function clearData(){if(!confirm('読み込んだデータをすべて削除しますか？'))return;state.transactions=[];state.assets=[];state.loadedFiles.clear();state.importMessages=[];state.transactionPage=1;state.demo=false;document.querySelector('#fileInput').value='';document.querySelector('#emptyFileInput').value='';document.querySelector('#folderInput').value='';document.querySelector('#emptyFolderInput').value='';document.querySelector('#search').value='';document.querySelector('#dashboard').hidden=true;document.querySelector('#demoBadge').hidden=true;document.querySelector('#demoNotice').hidden=true;document.querySelector('#emptyState').hidden=false;document.querySelector('#clearData').disabled=true}
  document.querySelector('#fileInput').addEventListener('change',e=>load(e.target.files));document.querySelector('#emptyFileInput').addEventListener('change',e=>load(e.target.files));document.querySelector('#folderInput').addEventListener('change',e=>load(e.target.files));document.querySelector('#emptyFolderInput').addEventListener('change',e=>load(e.target.files));document.querySelector('#demoData').addEventListener('click',loadDemoData);document.querySelector('#emptyDemoData').addEventListener('click',loadDemoData);document.querySelector('#clearData').addEventListener('click',clearData);document.querySelector('#monthSelect').addEventListener('change',()=>{state.transactionPage=1;renderCategories();renderTransactions()});document.querySelector('#search').addEventListener('input',()=>{state.transactionPage=1;renderTransactions()});document.querySelector('#transactionPagination').addEventListener('click',event=>{const direction=event.target.dataset.page;if(!direction)return;state.transactionPage+=direction==='next'?1:-1;renderTransactions()});
 const isGitHubPages=location.hostname.endsWith('.github.io')||location.hostname==='github.io';
 if(new URLSearchParams(location.search).get('demo')==='1'||isGitHubPages)loadDemoData();else autoLoadCsvs();
