const state={transactions:[],assets:[],loadedFiles:new Set(),transactionPage:1};
const yen=n=>new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0}).format(n);
const text=s=>String(s??'').trim();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function parseCSV(s){const rows=[];let row=[],cell='',quote=false;for(let i=0;i<s.length;i++){const c=s[i],n=s[i+1];if(c==='"'){if(quote&&n==='"'){cell+='"';i++}else quote=!quote}else if(c===','&&!quote){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!quote){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(x=>text(x))){rows.push(row)}row=[];cell=''}else cell+=c}if(cell||row.length){row.push(cell);rows.push(row)}return rows}
function decode(file){return file.arrayBuffer().then(b=>{const bytes=new Uint8Array(b);try{return new TextDecoder('utf-8',{fatal:true}).decode(bytes)}catch{return new TextDecoder('shift-jis').decode(bytes)}})}
function classify(headers,filename=''){const h=headers.join('');if(filename.includes('資産')||filename.includes('残高')||h.includes('資産')||h.includes('純資産'))return'assets';return'transactions'}
function parseFile(file){return decode(file).then(raw=>{const key=`${file.name}\0${raw}`;if(state.loadedFiles.has(key))return;state.loadedFiles.add(key);const rows=parseCSV(raw);if(!rows.length)return;const headers=rows[0].map(text);const type=classify(headers,file.name);if(type==='assets'){const date=headers.findIndex(x=>x.includes('日付'));const total=headers.findIndex(x=>x.includes('合計')||x.includes('総額')||x.includes('資産'));const incoming=rows.slice(1).map(r=>({date:text(r[date]),total:Number(text(r[total]).replace(/,/g,'')),breakdown:r.slice(1).map(v=>Number(text(v).replace(/,/g,''))||0)})).filter(x=>x.date&&Number.isFinite(x.total));state.assets.push(...incoming);}else{const target=headers.findIndex(x=>x.includes('計算対象'));const date=headers.findIndex(x=>x.includes('日付'));const content=headers.findIndex(x=>x.includes('内容')||x.includes('摘要'));const amount=headers.findIndex(x=>x.includes('金額'));const category=headers.findIndex(x=>x.includes('大項目')||x.includes('カテゴリ'));const incoming=rows.slice(1).filter(r=>target<0||text(r[target])==='1').map(r=>({date:text(r[date]),content:text(r[content]),category:text(r[category])||'未分類',amount:Number(text(r[amount]).replace(/,/g,''))})).filter(x=>x.date&&Number.isFinite(x.amount));state.transactions.push(...incoming);}})}
 function render(){document.querySelector('#emptyState').hidden=true;document.querySelector('#dashboard').hidden=false;document.querySelector('#clearData').disabled=state.transactions.length===0&&state.assets.length===0;const ts=state.transactions;const income=ts.filter(x=>x.amount>0).reduce((a,x)=>a+x.amount,0),expense=ts.filter(x=>x.amount<0).reduce((a,x)=>a+Math.abs(x.amount),0);document.querySelector('#income').textContent=yen(income);document.querySelector('#expense').textContent=yen(expense);document.querySelector('#balance').textContent=yen(income-expense);document.querySelector('#transactionCount').textContent=`明細 ${ts.length.toLocaleString()}件`;document.querySelector('#period').textContent=ts.length?`${ts.map(x=>x.date).sort()[0]} 〜 ${ts.map(x=>x.date).sort().at(-1)}`:'—';
const months=[...new Set(ts.map(x=>x.date.slice(0,7)))].sort().reverse();const select=document.querySelector('#monthSelect');select.innerHTML='<option value="all">全期間</option>'+months.map(m=>`<option>${m}</option>`).join('');renderCategories();renderTransactions();renderAssets()}
function filtered(){const m=document.querySelector('#monthSelect').value;return state.transactions.filter(x=>m==='all'||x.date.startsWith(m))}
function renderCategories(){const sums={};filtered().filter(x=>x.amount<0).forEach(x=>sums[x.category]=(sums[x.category]||0)+Math.abs(x.amount));const data=Object.entries(sums).sort((a,b)=>b[1]-a[1]).slice(0,8),max=data[0]?.[1]||1;document.querySelector('#categoryChart').innerHTML=data.length?data.map(([k,v])=>`<div class="bar-row"><span class="bar-label" title="${esc(k)}">${esc(k)}</span><div class="bar-track"><div class="bar-fill" style="width:${v/max*100}%"></div></div><span class="bar-value">${yen(v)}</span></div>`).join(''):'<p class="muted">支出データがありません</p>'}
function renderTransactions(){const q=document.querySelector('#search').value.toLowerCase();const rows=filtered().filter(x=>`${x.content} ${x.category}`.toLowerCase().includes(q)).sort((a,b)=>b.date.localeCompare(a.date));const pageSize=300;const pageCount=Math.max(1,Math.ceil(rows.length/pageSize));state.transactionPage=Math.min(state.transactionPage,pageCount);const start=(state.transactionPage-1)*pageSize;const visible=rows.slice(start,start+pageSize);document.querySelector('#transactions').innerHTML=visible.map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(x.content)||'—'}</td><td>${esc(x.category)}</td><td class="right ${x.amount>=0?'positive':'negative'}">${x.amount>=0?'+':''}${yen(x.amount)}</td></tr>`).join('')||'<tr><td colspan="4" class="muted">該当する明細がありません</td></tr>';const pagination=document.querySelector('#transactionPagination');pagination.innerHTML=rows.length>pageSize?`<span aria-live="polite">${start+1}〜${Math.min(start+pageSize,rows.length)}件 / ${rows.length}件</span><button type="button" data-page="prev" ${state.transactionPage===1?'disabled':''}>前の300件</button><span>ページ ${state.transactionPage} / ${pageCount}</span><button type="button" data-page="next" ${state.transactionPage===pageCount?'disabled':''}>次の300件</button>`:''}
function renderAssets(){if(!state.assets.length)return;const data=state.assets.slice().sort((a,b)=>a.date.localeCompare(b.date));const max=Math.max(...data.map(x=>x.total)),min=Math.min(...data.map(x=>x.total));const labels=['合計','現金・預金','株式・現金','投資信託','年金','ポイント'];document.querySelector('#assetLatest').textContent=`最新 ${yen(data.at(-1).total)}`;document.querySelector('#assetChart').innerHTML=data.slice(-60).map(x=>`<div class="asset-bar" data-date="${esc(x.date)}" data-value="${x.total}" data-breakdown="${x.breakdown.join(',')}" title="${esc(x.date)}: ${yen(x.total)}" role="button" tabindex="0" aria-label="${esc(x.date)}の資産 ${yen(x.total)}" style="height:${Math.max(5,(x.total-min)/(max-min||1)*100)}%"></div>`).join('')+'<div id="assetTooltip" class="asset-tooltip"></div>';const tooltip=document.querySelector('#assetTooltip');document.querySelectorAll('.asset-bar').forEach(bar=>{bar.addEventListener('mouseenter',()=>{const values=bar.dataset.breakdown.split(',').map(Number);tooltip.innerHTML=`<b>${esc(bar.dataset.date)}</b><br>${labels.map((label,i)=>`${label}: ${yen(values[i]||0)}`).join('<br>')}`;tooltip.classList.add('visible')});bar.addEventListener('mouseleave',()=>tooltip.classList.remove('visible'));const selectMonth=()=>{const month=bar.dataset.date.slice(0,7);const select=document.querySelector('#monthSelect');if([...select.options].some(option=>option.value===month)){select.value=month;renderCategories();renderTransactions();document.querySelector('#transactions').scrollIntoView({behavior:'smooth',block:'start'})}};bar.addEventListener('click',selectMonth);bar.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();selectMonth()}})})}
async function load(files){for(const f of files)await parseFile(f);render()}
async function listCsvs(path){const response=await fetch(path);if(!response.ok)throw new Error('CSV directory unavailable');const html=await response.text();const links=[...html.matchAll(/href="([^"]+)"/gi)].map(m=>decodeURIComponent(m[1]));const files=[];for(const link of links){if(link==='../'||link.startsWith('?'))continue;const url=path+link;if(link.endsWith('/'))files.push(...await listCsvs(url));else if(link.toLowerCase().endsWith('.csv'))files.push(url)}return files}
async function autoLoadCsvs(){try{const urls=await listCsvs('csvs/');if(!urls.length)return;for(const url of urls){const response=await fetch(url);const blob=await response.blob();await parseFile(new File([blob],url.split('/').at(-1),{type:'text/csv'}))}render()}catch(error){console.info('csvs auto-load skipped:',error.message)}}
function clearData(){if(!confirm('読み込んだデータをすべて削除しますか？'))return;state.transactions=[];state.assets=[];state.loadedFiles.clear();state.transactionPage=1;document.querySelector('#fileInput').value='';document.querySelector('#emptyFileInput').value='';document.querySelector('#folderInput').value='';document.querySelector('#emptyFolderInput').value='';document.querySelector('#search').value='';document.querySelector('#dashboard').hidden=true;document.querySelector('#emptyState').hidden=false;document.querySelector('#clearData').disabled=true}
  document.querySelector('#fileInput').addEventListener('change',e=>load(e.target.files));document.querySelector('#emptyFileInput').addEventListener('change',e=>load(e.target.files));document.querySelector('#folderInput').addEventListener('change',e=>load(e.target.files));document.querySelector('#emptyFolderInput').addEventListener('change',e=>load(e.target.files));document.querySelector('#clearData').addEventListener('click',clearData);document.querySelector('#monthSelect').addEventListener('change',()=>{state.transactionPage=1;renderCategories();renderTransactions()});document.querySelector('#search').addEventListener('input',()=>{state.transactionPage=1;renderTransactions()});document.querySelector('#transactionPagination').addEventListener('click',event=>{const direction=event.target.dataset.page;if(!direction)return;state.transactionPage+=direction==='next'?1:-1;renderTransactions()});
autoLoadCsvs();
